{
    products {
        _id
        title
        imageURL
        short_text
        text
        suplier {
            first_name
            last_name
        }
        category {
            title
            _id
        }
    }
}
